all:
  hosts:
    web01:
      ansible_host: 172.31.23.137
    web02:
      ansible_host: 172.31.17.193
    db01:
      ansible_host: 172.31.19.79
  children:
    websrvgrp:
      hosts:
        web01:
        web02:
    dbsrvgrp:
      hosts:
        db01:
    dc_ohio:
      children:
        websrvgrp:
        dbsrvgrp:
      vars:
        ansible_user: centos
        ansible_ssh_private_key_file: vprofile-key.pem